-- =====================================================================
--  Esquema de base de datos AMJP para Supabase (PostgreSQL)
--  Pegar y ejecutar en:  Supabase → SQL Editor → New query → Run
--  Al final registra el usuario admin del panel.
-- =====================================================================

-- Formato de fecha/hora igual al que usa la app: 'YYYY-MM-DD HH24:MI:SS'
-- (se define como valor por defecto en las columnas created_at/updated_at).

-- ---------- Panel: usuarios admin ----------
CREATE TABLE IF NOT EXISTS users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')
);

-- ---------- Noticias / Resoluciones / Cursos / Eventos / Deportes ----------
CREATE TABLE IF NOT EXISTS articles (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section    text NOT NULL CHECK (section IN ('noticias','resoluciones','cursos','eventos','deportes')),
  d          text NOT NULL,
  t          text NOT NULL,
  img        text,
  body       text NOT NULL DEFAULT '[]',
  created_at text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_articles_section ON articles(section, d DESC);

-- ---------- Galería ----------
CREATE TABLE IF NOT EXISTS gallery_albums (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug       text UNIQUE,
  title      text NOT NULL,
  thumb      text,
  date       text,
  intro      text,
  sort_order integer NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS gallery_photos (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id   bigint NOT NULL REFERENCES gallery_albums(id) ON DELETE CASCADE,
  big        text NOT NULL,
  thumb      text,
  caption    text,
  sort_order integer NOT NULL DEFAULT 0
);

-- ---------- Comisión Directiva ----------
CREATE TABLE IF NOT EXISTS cd_sections (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS cd_rows (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id bigint NOT NULL REFERENCES cd_sections(id) ON DELETE CASCADE,
  sort_order integer NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS cd_cells (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  row_id     bigint NOT NULL REFERENCES cd_rows(id) ON DELETE CASCADE,
  tag        text NOT NULL DEFAULT 'td',
  rowspan    integer NOT NULL DEFAULT 1,
  "text"     text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS cd_meta (
  id   integer PRIMARY KEY CHECK (id = 1),
  hero text
);

-- ---------- Estatutos ----------
CREATE TABLE IF NOT EXISTS estatutos (
  id   integer PRIMARY KEY CHECK (id = 1),
  html text NOT NULL DEFAULT ''
);

-- ---------- Expresidentes ----------
CREATE TABLE IF NOT EXISTS expresidentes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  big        text,
  thumb      text,
  name       text NOT NULL,
  period     text,
  sort_order integer NOT NULL DEFAULT 0
);

-- ---------- Beneficios ----------
CREATE TABLE IF NOT EXISTS beneficios (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      text NOT NULL,
  href       text,
  "desc"     text,
  active     integer NOT NULL DEFAULT 1,
  sort_order integer NOT NULL DEFAULT 0
);

-- ---------- Mensajes de formularios ----------
CREATE TABLE IF NOT EXISTS form_submissions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind       text NOT NULL,
  data       text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS'),
  read       integer NOT NULL DEFAULT 0
);

-- ===== Aula Virtual (plataforma de cursos) =====

CREATE TABLE IF NOT EXISTS students (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  email         text UNIQUE NOT NULL,
  matricula     text,
  password_hash text NOT NULL,
  active        integer NOT NULL DEFAULT 1,
  created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS course_modules (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id  bigint NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  title      text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_modules_course ON course_modules(course_id, sort_order);

CREATE TABLE IF NOT EXISTS course_lessons (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id   bigint NOT NULL REFERENCES course_modules(id) ON DELETE CASCADE,
  title       text NOT NULL,
  description text,
  video_path  text,
  is_live     integer NOT NULL DEFAULT 0,
  live_url    text,
  sort_order  integer NOT NULL DEFAULT 0,
  created_at  text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_lessons_module ON course_lessons(module_id, sort_order);

CREATE TABLE IF NOT EXISTS enrollments (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id  bigint NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  created_at text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(student_id, course_id)
);
CREATE INDEX IF NOT EXISTS idx_enrollments_student ON enrollments(student_id);

CREATE TABLE IF NOT EXISTS lesson_progress (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  lesson_id  bigint NOT NULL REFERENCES course_lessons(id) ON DELETE CASCADE,
  completed  integer NOT NULL DEFAULT 0,
  updated_at text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(student_id, lesson_id)
);

-- =====================================================================
--  REGISTRO DEL LOGIN ADMIN
--  Usuario: admin   |   Contraseña: amjp2026
--  (hash scrypt, mismo formato que usa el panel: "salt:hash")
--  ⚠ Cambiá la contraseña para producción (avisame y te genero otro hash).
-- =====================================================================
INSERT INTO users (username, password_hash)
VALUES (
  'admin',
  '6b9d5a9d81c1e2d2b5508de9e81751a2:10bd980a9e507e79eb7f182263609487b6b37734451405e4a8b4429a0ab08f010bd4a5fb4fb65c3090202d5adaf6b8cfb28497c3bcd2c08b6732432bef90d945'
)
ON CONFLICT (username) DO NOTHING;
